language: node_js
node_js:
- '8'
install:
- npm install
script: npm test
before_deploy: npm run pack
deploy:
  - provider: releases
    api_key:
      secure: "Ids51LgFBEoOR1q1DrmxNRP/ryPHPEAuf7vsO7aBVy+qFwcaRzwmvxvjPVa5907Sv7zkccg+qbFW9+W1HQ7IYi4nyaX/4o8WaxQgev2aki2KD5ztQlsWeGRcquAZfZplLrUbXJkEW8cnXcGIE8QKc08yiQa25+3s8fsBi797z8pj04iLAvkK600lFbKls90rQH7FsIlIrc0LarvNNFqEi/qtUoPeMQ6ksWoE1emvRZfLaIh8IIgzfN00MxX/hZb+50v2eZaypjfODZZL5GDvnCM+fofqCyEnJwo0JLxRHz7rHKN4/nAN6Rbvqx2bGQu7WtWCX3nT+u7rdgg3gjqR4oeHHpNqhalwXpfPWU/3G9HiyCSODqa/bps8FODM3hm8+LENQrsWYWZ6/mLxY76F97MqHTQHSz4rB74aKDc+nZ1Teqw8oykC0T47JwguH+ZIfKt7bOW9awWFkEbPSOrWNGQV7ZVjhxKlr4bazeYUyHFhTLjkawH8P1jRSt3H2a+AZES5cDuXEwKER7I7hZU7FCNNbFxUHJo0rSG/dynFk9jmiSmUELAKkkj/C0UTP3r55Zkq7LleOlfhXELmk6cEr+uQIAm/OzQ/CKL+5Vq1uhSNqmdxFGURHQNUQrv2tmysyNEzo+N9mwtOQH43JRjT7PnhuTWI/BOrqi8kk7csUaw="
    file_glob: true
    file: "packed/*"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    email: datahub@datopian.com
    api_key:
      secure: T/Ht/gSlWDHpfnsIhvenMTp6hQDyds/UviSyVSfAqaD0j+Q5kR0UVPwzvon6WF1FQKIiuJTBkGSJexM4gejH+JFf7H2qALEx9hRAk4/hzjg96cFEO0pRtxLjgx2RUGylVhMyGQ4g0rxefgtFPicRBNzWQCfeXa5LoosqCJ8RCQkrfffTequqqE9UXH1GTTtpOrpUrXswU0D85Hhnf5OkG7AH6/0yMd+KzXm6xCr8elR9hLWc6ervo8z6KAx1S8GWSfeaCvPqNUwnEvFibqkXxkxnDQssoCTCBeoJng2lsWkDpBiH4nKLgweN8tbN85zpFgSuT8H3tosUIe6JVYPRkSofYcDewnjSJcAX37wSI4MQMmynZWhTij2c2X9809BxT7MtojpxXeADIvTxxRmfmefcCPr/HrQvzYMN1w4NR/YI/XoyuLTpFezBDAodIq87aeR3Y4fAbLEZy0FJ/kvGLQTJcS25mPBScmVJ7+zTm+S8rE5Me9KK/sC4IFRR2q0fT4jwGttsH5b7T9YJ/clAGAQSmxo+3GQkmFe3q0inY0I5Amnv7ib+5Y6uGuW5o3TLWUDvd3Svae8OHu1ZNrmj9qyYH1KEMrO36kcNSAMBhWtQfYCXrUf2tej7vSC0Tflw4Tn4A8fQ5Smcy0DiLzuUXAxIUYHY7hzH6NGN5WWV5Tw=
    on:
      tags: true